---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  annotations: 
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: productcatalogservice
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550