stages:
  - deploy

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  APP_NAME: my-first-app

deploy:
  stage: deploy
  image: alpine/helm:3.2.1
  script:
    - helm install ${APP_NAME} --namespace ${APP_NAME} deploy/00shop/
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always