---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  annotations: 
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: checkoutservice
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050