---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
  annotations: 
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: shippingservice
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051