apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: default
rules:
# Just an example, feel free to change it
- apiGroups: [""]
  resources: ["pods", "nodes"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
  
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io
