---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  annotations: 
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - name: redis
    port: 6379
    targetPort: 6379