---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  annotations: 
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app: currencyservice
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000