apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
  name: prometheus-nginx
  namespace: istio-system
spec:
  rules:
    - host: kibana
      http:
        paths:
          - backend:
              service:
                name: efk-kibana
                port:
                  number: 30010
            path: /
            pathType: Prefix
    - host: prometheus
      http:
        paths:
          - backend:
              service:
                name: prometheus
                port:
                  number: 9090
            path: /
            pathType: Prefix
    - host: grafana
      http:
        paths:
          - backend:
              service:
                name: grafana
                port:
                  number: 3000
            path: /
            pathType: Prefix
    - host: kiali
      http:
        paths:
          - backend:
              service:
                name: kiali
                port:
                  number: 20001
            path: /
            pathType: Prefix

