stages:
  - stage
  - prod

stage:
  stage: stage
  when: manual
  image: alpine/helm:3.2.1
  before_script:
    - apk add -U openssl curl tar gzip bash ca-certificates git
    - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
    - apk add glibc-2.23-r3.apk
    - curl https://storage.googleapis.com/pub/gsutil.tar.gz | tar -xz -C $HOME
    - export PATH=${PATH}:$HOME/gsutil
    #  Kubectl install
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl version --client
  script: 
    - git clone http://130.193.45.218/$CI_PROJECT_NAMESPACE/shop.git
    - helm dep update shop/00shop
    - if helm install shop shop/00shop -n default  ; then echo "release is installed"  ; else helm upgrade shop shop/00shop -n default ;fi

prod:
  stage: prod
  when: manual
  image: alpine/helm:3.2.1
  before_script:
    - apk add -U openssl curl tar gzip bash ca-certificates git
    - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
    - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk
    - apk add glibc-2.23-r3.apk
    - curl https://storage.googleapis.com/pub/gsutil.tar.gz | tar -xz -C $HOME
    - export PATH=${PATH}:$HOME/gsutil
    #  Kubectl install
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - kubectl version --client
  script: 
    - if kubectl get namespaces prod; then echo "ns prod is already exist" ; else kubectl create namespace prod && kubectl label namespace prod istio-injection=enabled ; fi 
    - git clone http://130.193.45.218/$CI_PROJECT_NAMESPACE/shop.git
    - helm dep update shop/00shop
    - if helm install shop shop/00shop -n prod  ; then echo "release is installed"  ; else helm upgrade shop shop/00shop -n prod ;fi
